import React, {
  useState
} from "react";

import {
  Row,
  Col,
  Card,
  CardBody
} from "reactstrap";

import MDBDataTableComponent from "../../../components/common/MDBDataTable/MDBDataTableComponent";

import ReportSummaryCards from "../../../components/DOReport/ReportSummaryCards";

import ReportFilters from "../../../components/DOReport/ReportFilters";

import BreedUtilizationChart from "../../../components/DOReport/BreedUtilizationChart";

import BlockWisePerformanceChart from "../../../components/DOReport/BlockWisePerformanceChart";

import MonthlyDistributionChart from "../../../components/DOReport/MonthlyDistributionChart";

import ReportActionButtons from "../../../components/DOReport/ReportActionButtons";

import RecentReportActivity from "../../../components/DOReport/RecentReportActivity";

import ExportReportModal from "../../../components/DOReport/ExportReportModal";

const DOReport = () => {

  const [exportModal, setExportModal] =
    useState(false);

  const columns = [

    {
      label: "Report Name",
      field: "reportName"
    },

    {
      label: "Category",
      field: "category"
    },

    {
      label: "Generated Date",
      field: "generatedDate"
    },

    {
      label: "Generated By",
      field: "generatedBy"
    },

    {
      label: "Actions",
      field: "action"
    }

  ];

  const rows = [

    {
      reportName:
        "Monthly Utilization Report",

      category:
        "Utilization",

      generatedDate:
        "2026-05-20",

      generatedBy:
        "District Officer",

      action: (
        <ReportActionButtons />
      )
    },

    {
      reportName:
        "Redistribution Analysis",

      category:
        "Redistribution",

      generatedDate:
        "2026-05-18",

      generatedBy:
        "District Officer",

      action: (
        <ReportActionButtons />
      )
    }

  ];

  return (
    <React.Fragment>
        <div className="district-reports-page">

        {/* HEADER */}

        <div className="page-header d-flex justify-content-between align-items-center mb-4">

            <div>

            <h3 className="fw-bold mb-1">

                District Reports

            </h3>

            <p className="text-muted mb-0">

                Monitor utilization, allocation and redistribution analytics

            </p>

            </div>

            <button
            className="btn btn-primary"
            onClick={() =>
                setExportModal(true)
            }
            >

            <i className="bi bi-download me-2"></i>

            Export Report

            </button>

        </div>

        {/* SUMMARY */}

        <ReportSummaryCards />

        {/* FILTERS */}

        <ReportFilters />

        {/* CHARTS */}

        <Row className="mb-4">

            <Col lg="4" className="mb-4">

            <BreedUtilizationChart />

            </Col>

            <Col lg="4" className="mb-4">

            <BlockWisePerformanceChart />

            </Col>

            <Col lg="4" className="mb-4">

            <MonthlyDistributionChart />

            </Col>

        </Row>

        {/* TABLE */}

        <Card className="border-0 shadow-sm">

            <CardBody>

            <MDBDataTableComponent

                columns={columns}

                rows={rows}

                searchable={true}

                pagination={true}

                exportable={true}

                columnVisibility={true}

                tableHeight="500px"

            />

            </CardBody>

        </Card>

        {/* ACTIVITIES */}

        <RecentReportActivity />

        {/* EXPORT */}

        <ExportReportModal

            isOpen={exportModal}

            toggle={() =>
            setExportModal(!exportModal)
            }

        />

        </div>
    </React.Fragment>
  );

};

export default DOReport;